// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE5pJusWsl3CEcZSMPYezrvEEHUI_TkP8',
    appId: '1:409553687921:web:4f15c4381a9a916e2412d0',
    messagingSenderId: '409553687921',
    projectId: 'charged-gravity-392618',
    authDomain: 'charged-gravity-392618.firebaseapp.com',
    storageBucket: 'charged-gravity-392618.appspot.com',
    measurementId: 'G-D275T8N8C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXo9APV6iHgDOu6QFMfnBuR9-YDQgd8No',
    appId: '1:409553687921:android:5fddced853b8da622412d0',
    messagingSenderId: '409553687921',
    projectId: 'charged-gravity-392618',
    storageBucket: 'charged-gravity-392618.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq_eTPZYvh6WG9oOAoXXFMOr4rK75Go58',
    appId: '1:409553687921:ios:80d538777fa476cc2412d0',
    messagingSenderId: '409553687921',
    projectId: 'charged-gravity-392618',
    storageBucket: 'charged-gravity-392618.appspot.com',
    iosClientId: '409553687921-7nd79edvcehqj3da0q2gs7m5jmhs38si.apps.googleusercontent.com',
    iosBundleId: 'com.example.fire2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq_eTPZYvh6WG9oOAoXXFMOr4rK75Go58',
    appId: '1:409553687921:ios:c6d12409eb8601902412d0',
    messagingSenderId: '409553687921',
    projectId: 'charged-gravity-392618',
    storageBucket: 'charged-gravity-392618.appspot.com',
    iosClientId: '409553687921-8chumga9dfscg7p27lbk4fpjhhgscjng.apps.googleusercontent.com',
    iosBundleId: 'com.example.fire2023.RunnerTests',
  );
}
